# Travis-CI build script

language: cpp

sudo: false
dist: bionic

matrix:
  include:
    # gcc 4.9 with AddressSanitizer, Debug
    - env: CMAKE_CC="gcc-8" CMAKE_CXX="g++-8" BUILD_TYPE="Debug" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: &gcc8
        apt:
          packages:
           - g++-8

    # gcc 7, Debug with OpenMPI
    - env: CMAKE_CC="gcc" CMAKE_CXX="g++" BUILD_TYPE="Debug" COMPILER_FLAGS="-O1"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - openmpi-bin
            - libopenmpi-dev

    # gcc, Release
    - env: CMAKE_CC="gcc-8" CMAKE_CXX="g++-8" BUILD_TYPE="Release" COMPILER_FLAGS=""
      os: linux
      addons: &gcc8
        apt:
          packages:
            - g++-8

    # clang
    - env: CMAKE_CC="clang" CMAKE_CXX="clang++" BUILD_TYPE="Debug" COMPILER_FLAGS=""
      os: linux

before_script:

  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  # enable -Werror on master branch
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      COMPILER_FLAGS="$COMPILER_FLAGS -Werror";
    fi

  # configure
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      -DSAMPLING_BUILD_TESTS=ON
      $CMAKE_ARGS ..

script:
  - ctest
      -DCTEST_SITE:STRING="travis-$TRAVIS_REPO_SLUG"
      -DCTEST_BUILD_NAME:STRING="$TRAVIS_OS_NAME-$CMAKE_CC-$BUILD_TYPE"
      -S ../cmake/script.ctest -VV
